spring:
  kafka:
    consumer:
      group-id: transaction-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: kafka:29092
  application:
    name: codechallenge
  datasource:
    url: jdbc:mysql://db:3306/core_challenge?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true&characterEncoding=utf8
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: PoolNameSpringBootHikariCP-${random.value}
      max-lifetime: 60000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
      enabled: 'true'
logging:
  pattern:
    dateformat: hh:mm
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %level %class.%method - %msg%n"
  level:
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE
    '[com.zaxxer.hikari.HikariConfig]': DEBUG
  file:
    name: ./logs/logfile.log
server:
  port: "8092"
