spring:
  application:
    name: '@project.artifactId@'
  # Configuración de Kafka
  kafka:
    bootstrap-servers: localhost:9092
    producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
    producer.value-serializer: org.apache.kafka.common.serialization.StringSerializer
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/transactiondb
    username: postgres
    password: postgres

server:
  port: 8001

application:
  api:
    path: '/api/v1/transaction'
