FROM alpine:3.18.3

RUN apk add --no-cache openjdk17 maven

WORKDIR /app

COPY ./codechallenge .

RUN mvn clean package -D skipTests -P docker

FROM alpine:3.18.3

RUN apk add --no-cache openjdk17

WORKDIR /app

COPY --from=0 /app/target/codechallenge-0.0.1-SNAPSHOT.jar .

ENV SPRING_PROFILES_ACTIVE=docker

CMD ["/usr/bin/java", "-jar", "codechallenge-0.0.1-SNAPSHOT.jar"]